### ISSUE TITLE
Magic numbers ?

### ISSUE THREAD

**Issue by kounkou** [duboviy/dist#2]
Hey Duboviy,

I find your projects awesome !
Would like to participate a bit.
Why using those magic numbers here ? Seems to me that we can make that code more generic right ?

https://github.com/duboviy/dist/blob/dc41696801eb78ce47ef3964fd5e057ef4a971b5/src/py2/dist.c#L28

**Comment by duboviy** [comment]
Hi Jacques,

Totally agree. 
Kindly ask you to create a pull request if functionality is not broken, I'll review and merge it.

**Comment by kounkou** [comment]
Hi Duboviy,

Perfect, I added a first PR #4
In that first PR, I removing the hard coded constants and creating a new file to hold them in a
cleaner way. Let me know what you think.

**Comment by duboviy** [comment]
@kounkou Nice catch and great changes! 👍 👍 👍  Thank you so much for your contribution! Feel free to create more PRs here and also within other repos. I really appreciate it, Jacques!
