### ISSUE TITLE
Contract programming

### ISSUE THREAD

**Issue by kounkou** [duboviy/dist#3]
Hi Duboviy,

Amazing work here.
I have one question though... wouldn't be more interesting to use programmation by contract and protect the function in case the given pointers aren't valid ?
I mean, using something like 
```
assert(self != NULL && args != NULL);
```

https://github.com/duboviy/dist/blob/dc41696801eb78ce47ef3964fd5e057ef4a971b5/src/py3/dist.c#L32

**Comment by duboviy** [comment]
Hi Jacques,

Thanks a lot, it's nice to hear these words from you.

Totally agree. 
Frankly speaking, I don't have time to actively participate in these projects, but feel free to contribute to this repo. Kindly ask you to create a pull request if functionality is not broken, I'll review and merge it.
