### ISSUE TITLE
is M_PI include actually linking to the dist.c file ?

### ISSUE THREAD

**Issue by kounkou** [duboviy/dist#5]
Hi there Duboviy

I just realized the M_PI is actually binding to the #include made within dist.c
This is a tight coupling of the dist.h with the dist.c
I feel, I shall include the math header inside the dist.h instead.

https://github.com/duboviy/dist/blob/965cffe703da81c82d7b8877eb206aa6a7dea05b/src/py2/dist.h#L8

**Comment by kounkou** [comment]
The PR #6 solves this issue.

**Comment by duboviy** [comment]
Done.
